### ISSUE TITLE
My Sales Module > Customer and Sales Module > Product Error when I installed Fleet Management

### ISSUE THREAD

**Issue by bbserrano21** [JayVora-SerpentCS/fleet_management#3]
Hi SerpenctCS Team,

Good day, I have an issue when I installed your Fleet_Management Module. When I installed it, suddenly my SALES Module > Customer and SALES Module > Product , got this error below. If I uninstall your module. everything will be fine. See error below.

Environment
Ubuntu 18.04 (Updated) 
Odoo 11.0-20180814 Version

Thanks and Regards,
Bren

Error:
Uncaught TypeError: Cannot read property '1' of undefined

http://10.47.1.43:8069/web/content/511-824a8c9/web.assets_backend.js:1186
Traceback:
TypeError: Cannot read property '1' of undefined
    at http://10.47.1.43:8069/web/content/511-824a8c9/web.assets_backend.js:1186:382
    at Function._.each._.forEach (http://10.47.1.43:8069/web/content/510-be42584/web.assets_common.js:12:558)
    at Object.<anonymous> (http://10.47.1.43:8069/web/content/511-824a8c9/web.assets_backend.js:1186:244)
    at Object.<anonymous> (http://10.47.1.43:8069/web/content/510-be42584/web.assets_common.js:802:681)
    at fire (http://10.47.1.43:8069/web/content/510-be42584/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://10.47.1.43:8069/web/content/510-be42584/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) [as resolve] (http://10.47.1.43:8069/web/content/510-be42584/web.assets_common.js:803:56)
    at Object.<anonymous> (http://10.47.1.43:8069/web/content/510-be42584/web.assets_common.js:3869:358)
    at Object.<anonymous> (http://10.47.1.43:8069/web/content/510-be42584/web.assets_common.js:802:681)
    at fire (http://10.47.1.43:8069/web/content/510-be42584/web.assets_common.js:796:299)

**Comment by JayVora-SerpentCS** [comment]
@YogendrasinhChavda Pls checkk.

**Comment by YogendrasinhChavda** [comment]
@JayVora-SerpentCS 
Sure, sir, I will Check and fix it.

**Comment by YogendrasinhChavda** [comment]
Hello @bbserrano21 

We traced issue in our local system by creating the fresh databases with demo data and without demo data and installed fleet modules with the sale management module. it is working fine, Sales => Customer and Sales => Products menu also working fine.

Please take the latest pull of the fleet_management (11.0) branch and check it.

Our System Environment
Ubuntu: 16.04 LTS
Odoo 11.0 CE Latest Version

Thank you.
