### ISSUE TITLE
odoo server error while installing fleet management module in odoo10 CE

### ISSUE THREAD

**Issue by AURANGZEBB** [JayVora-SerpentCS/fleet_management#41]
Hi, I am installing fleet management module in odoo 10 CE but getting this server error even after installing all the dependencies. Here find below the error:

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo10/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo10/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo10/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo10/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo10/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo10/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo10/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo10/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo10/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo10/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo10/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo10/odoo/addons/base/module/module.py", line 413, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo10/odoo/addons/base/module/module.py", line 495, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo10/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo10/odoo/modules/loading.py", line 377, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo10/odoo/modules/loading.py", line 270, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo10/odoo/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo10/odoo/modules/loading.py", line 96, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo10/odoo/tools/convert.py", line 840, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/opt/odoo10/odoo/tools/convert.py", line 896, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading fleet_operations failed: file fleet_operations/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'model_edit_parts_contact_team_trip' in field 'Object'
Missing required value for the field 'Object' (model_id)
No matching record found for external id 'model_edit_parts_contact_team_trip' in field 'Object'
Missing required value for the field 'Object' (model_id)

**Comment by ChavdaRiddhi** [comment]
hello @aurangzaibbhatti  we will check and resolve that as soon as possible.
thanks

**Comment by ChavdaRiddhi** [comment]
hello @aurangzaibbhatti 
issue resolved, please take latest updated code of branch 10.0 and check.
Thanks

**Comment by AURANGZEBB** [comment]
Hi, @ChavdaRiddhi 
I will check and let you know. Thanks a lot. :)

**Comment by AURANGZEBB** [comment]
Hi, @ChavdaRiddhi 
Thanks, Above error has resolved but now appears following error. 

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo10/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo10/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo10/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo10/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo10/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo10/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo10/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo10/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo10/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo10/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo10/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo10/odoo/addons/base/module/module.py", line 413, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo10/odoo/addons/base/module/module.py", line 495, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo10/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo10/odoo/modules/loading.py", line 377, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo10/odoo/modules/loading.py", line 270, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo10/odoo/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo10/odoo/modules/loading.py", line 96, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo10/odoo/tools/convert.py", line 846, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo10/odoo/tools/convert.py", line 916, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo10/odoo/tools/convert.py", line 797, in parse
    self.parse(rec, mode)
  File "/opt/odoo10/odoo/tools/convert.py", line 800, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo10/odoo/tools/convert.py", line 323, in _tag_report
    id = self.env['ir.model.data']._update("ir.actions.report.xml", self.module, res, xml_id, noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo10/odoo/addons/base/ir/ir_model.py", line 1252, in _update
    record = record.create(values)
  File "/opt/odoo10/odoo/addons/base/ir/ir_actions.py", line 50, in create
    res = super(IrActions, self).create(vals)
  File "/opt/odoo10/odoo/models.py", line 3876, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo10/odoo/models.py", line 3956, in _create
    self._check_selection_field_value(name, val)
  File "/opt/odoo10/odoo/models.py", line 2133, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/opt/odoo10/odoo/fields.py", line 1809, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ParseError: "Wrong value for ir.actions.report.xml.report_type: 'xlsx'" while parsing /opt/odoo10/custom_addons/fleet_operations/report/report_xlsx.xml:13, near
<report id="fleet_history_report_xlsx" model="fleet.vehicle" string="Fleet History" report_type="xlsx" name="fleet.history.xls" file="fleet.history.xls" attachment_use="False"/>

**Comment by ChavdaRiddhi** [comment]
Hello, @ABXTTI  
we tested issue as per you mentioned but we are not faced same issue in our system.it's working fine.
As per the error log I thought you missed below mention module.
https://apps.odoo.com/apps/modules/10.0/report_xlsx/
If that module is not available in your addons then download it first, add with addons and then check.
Thanks
