### ISSUE TITLE
v13 -Fleet operations module returns error while the repairs is not completed and pressed button "Done". 

### ISSUE THREAD

**Issue by mita4kata** [JayVora-SerpentCS/fleet_management#45]
HI, 
the Fleet operations module returns error while the repairs is not completed and pressed button "Done". 

Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/data/addons/13.0/fleet_operations/models/fleet_service.py", line 224, in action_done
    context.update({'work_order_id': work_order.id})
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/tools/misc.py", line 1003, in update
    raise NotImplementedError("'update' not supported on frozendict")
NotImplementedError: 'update' not supported on frozendict

**Comment by ChavdaRiddhi** [comment]
Hello  @mita4kata ,
issue resolved. Please take the latest updated code of branch 13.0.

**Comment by mita4kata** [comment]
Hi, 
now we are getting another error message . 

Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/data/addons/13.0/fleet_operations/models/fleet_service.py", line 224, in action_done
    resource_id = model_data_ids.read(['res_id'])[0]['res_id']
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/tools/misc.py", line 1003, in update
    raise NotImplementedError("'update' not supported on frozendict")
NotImplementedError: 'update' not supported on frozendict

**Comment by mita4kata** [comment]
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/data/addons/13.0/fleet_operations/models/fleet_service.py", line 224, in action_done
    resource_id = model_data_ids.read(['res_id'])[0]['res_id']
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/tools/misc.py", line 1003, in update
    raise NotImplementedError("'update' not supported on frozendict")
NotImplementedError: 'update' not supported on frozendict

**Comment by mita4kata** [comment]
File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/api.py", line 382, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "/opt/bitnami/apps/odoo/data/addons/13.0/fleet_operations/models/fleet_service.py", line 224, in action_done
resource_id = model_data_ids.read(['res_id'])[0]['res_id']
File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/tools/misc.py", line 1003, in update
raise NotImplementedError("'update' not supported on frozendict")
NotImplementedError: 'update' not supported on frozendict

**Comment by ChavdaRiddhi** [comment]
hello @mita4kata ,
we already checked with latest updated fleet management 13.0 branch .we didn't faced any issue 
if you still facing the issue you can open new issue with proper steps and if possible then you can attach small video clip about that.
Thanks
