### ISSUE TITLE
Error saving Vehicle 

### ISSUE THREAD

**Issue by jayo2005** [JayVora-SerpentCS/fleet_management#49]
Using v13 of the vehicles_dealership module. When saving a Vehicle I get the following error.

```
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 385, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 365, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-158>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 314, in _model_create_single
    return create(self, arg)
  File "/odoo/custom/addons/vehicles_dealership/models/fleet_vehicle.py", line 25, in create
    create_fleet_vehicle=True)).create(vals)
  File "<decorator-gen-116>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 314, in _model_create_single
    return create(self, arg)
  File "/odoo/odoo-server/addons/fleet/models/fleet_vehicle.py", line 206, in create
    res = super(FleetVehicle, self).create(vals)
  File "<decorator-gen-109>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 268, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3736, in create
    for data in parent_data_list
  File "<decorator-gen-159>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 317, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/odoo/odoo-server/odoo/api.py", line 317, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/odoo/custom/addons/vehicles_dealership/models/fleet_vehicle.py", line 77, in create
    return super(ProductProduct, self).create(vals)
  File "<decorator-gen-123>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/odoo/odoo-server/addons/product/models/product.py", line 319, in create
    products = super(ProductProduct, self.with_context(create_product_product=True)).create(vals_list)
  File "<decorator-gen-109>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 268, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3736, in create
    for data in parent_data_list
  File "<decorator-gen-120>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/addons/product/models/product_template.py", line 374, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-109>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 268, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3742, in create
    records = self._create(data_list)
  File "/odoo/odoo-server/odoo/models.py", line 3814, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/odoo/odoo-server/odoo/fields.py", line 2230, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/odoo/odoo-server/odoo/fields.py", line 2242, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for product.template.type: 'product'
```

**Comment by YogendrasinhChavda** [comment]
Hello @jayo2005 ,
We will check and update you as soon as possible.
Thanks

**Comment by YogendrasinhChavda** [comment]
Hello @jayo2005 ,
As per you submitted issue log, issue was module dependency that is resolved now. ( https://github.com/JayVora-SerpentCS/fleet_management/pull/50 )

Please take latest code update of fleet management 13.0, upgrade module with your instance and check again. 

Thanks
