### ISSUE TITLE
Error while installing on Odoo 12.0 CE

### ISSUE THREAD

**Issue by revealmap** [JayVora-SerpentCS/fleet_management#55]
Dear,

I encouer an issue when trying to install the folowingws Apps on Odoo 12.0 Community Edition :

1. fleet Operation
2. fleet rental vehicle

Could you help me to fix this please?

I am looking for a gooa Apps to Manage cars Fleet, to rent cars and to manage bookings.

My Odoo labs runs on Windows server 2016 (on a personnal/local computer).

Attached are some captures and the errors messages.

thank you for your help

Fleet Operation error message:

Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 4, in <module>
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\fleet_operations\models\__init__.py", line 4, in <module>
    from . import fleet_extended
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\fleet_operations\models\fleet_extended.py", line 954, in <module>
    class FleetVehicleModel(models.Model):
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\fleet_operations\models\fleet_extended.py", line 970, in FleetVehicleModel
    image_128 = fields.Image(string="Image", readonly=False)
AttributeError: module 'odoo.fields' has no attribute 'Image'

Fleet Rental Vehicle error message:
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\registry.py", line 305, in init_models
    func()
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 2694, in update_db_foreign_keys
    sql.add_foreign_key(cr, self.relation, self.column2, comodel._table, 'id', 'cascade')
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\sql.py", line 159, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedTable: ERREUR:  la relation « _unknown » n'existe pas

**Comment by JayVora-SerpentCS** [comment]
@YogendrasinhChavda Can you check?
Thanks.

**Comment by YogendrasinhChavda** [comment]
Hello  @JayVora-SerpentCS Sir,
I checked fleet modules for odoo 12 CE with Ubuntu OS, its installed in fresh database without any issue.
I will check with windows OS and i will update.

Thank you.

**Comment by JayVora-SerpentCS** [comment]
@revealmap it looks like you have not been using the latest Odoo core code. May  we please request you to get the latest code and check? (use latest installer).
The error says about odoo.fields.Image not found, but it shud work on v13.
While, if you have latest v12 code, you are using the module of v13!
