### ISSUE TITLE
ValueError: Invalid field 'invoice_origin' on model 'account.move.line'

### ISSUE THREAD

**Issue by rpsjr** [JayVora-SerpentCS/fleet_management#56]
Steps to reproduce:
Create a vehicle;
Create a rent;
Try to invoice rent.

`Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/models.py", line 5189, in _update_cache
    field_values = [(fields[name], value) for name, value in values.items()]
  File "/opt/odoo/odoo/odoo/models.py", line 5189, in <listcomp>
    field_values = [(fields[name], value) for name, value in values.items()]
KeyError: 'invoice_origin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1331, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/fleet_management/fleet_rent/models/fleet_rent.py", line 832, in create_invoice
    acc_id = self.env['account.move'].create(inv_values)
  File "<decorator-gen-164>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo/addons/purchase/models/account_invoice.py", line 103, in create
    moves = super(AccountMove, self).create(vals_list)
  File "<decorator-gen-150>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/addons/account/models/account_move.py", line 1699, in create
    vals_list = self._move_autocomplete_invoice_lines_create(vals_list)
  File "/opt/odoo/odoo/addons/account/models/account_move.py", line 1665, in _move_autocomplete_invoice_lines_create
    move = self_ctx.new(new_vals)
  File "/opt/odoo/odoo/odoo/models.py", line 5547, in new
    record._update_cache(values, validate=False)
  File "/opt/odoo/odoo/odoo/models.py", line 5195, in _update_cache
    cache.set(self, field, field.convert_to_cache(value, self, validate))
  File "/opt/odoo/odoo/odoo/fields.py", line 2759, in convert_to_cache
    ids.add(comodel.new(command[2], ref=command[1]).id)
  File "/opt/odoo/odoo/odoo/models.py", line 5547, in new
    record._update_cache(values, validate=False)
  File "/opt/odoo/odoo/odoo/models.py", line 5191, in _update_cache
    raise ValueError("Invalid field %r on model %r" % (e.args[0], self._name))
ValueError: Invalid field 'invoice_origin' on model 'account.move.line'`

**Comment by YogendrasinhChavda** [comment]
Hello @rpsjr ,
Which Version of odoo you are using?

Fleet Management for version 14 is not Fully migrated yet. work is in progress.

Thanks

**Comment by rpsjr** [comment]
Hi YogendrasinhChavda,

Version 13.0!

**Comment by YogendrasinhChavda** [comment]
Hello @rpsjr 

Please take latest update and check.
