### ISSUE TITLE
Error while open report update next service day

### ISSUE THREAD

**Issue by kimbo23** [JayVora-SerpentCS/fleet_management#60]
while open report update next service day show this error:
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/extra-addons/fleet_operations/wizard/update_next_service.py", line 50, in default_get
    service = serv_obj.browse(self._context['active_id'])
KeyError: 'active_id'

**Comment by YogendrasinhChavda** [comment]
@kimbo23 you are using version 14 or 13?
Will update you with fix.

**Comment by kimbo23** [comment]
We are using Odoo 13

**Comment by kimbo23** [comment]
Other questions, can you work in other customization for fleet module?

**Comment by YogendrasinhChavda** [comment]
Yes, we are open to work with you for other development.
You can send your requirements on contact@serpentcs.com OR
We can communicate via y.chavda.serpentcs@gmail.com
